name: otomasi deploy server
on: 
  push:
    branches:
      - main
  pull_request:
    types: [synchronized]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd prj/
          rm -rf deployBE16
          git clone https://github.com/jackthepanda96/deployBE16.git
          cd deployBE16/
          docker stop ${{ secrets.CNAME }}
          docker rm ${{ secrets.CNAME }}
          docker rmi be16prj:alpine
          docker build be16prj:alpine .
          docker run --name ${{ secrets.CNAME }} -p 8000:8000 --link mysqlku -e DBUser=${{ secrets.DBUSER }} -e DBPassword=${{ secrets.DBPASSWORD }} -e DBHost=${{ secrets.DBHOST }} -e DBPort=${{ secrets.DBPORT }} -e DBName=${{ secrets.DBNAME }} -e JWT_SECRET= ${{ secrets.JWT }} be16prj:alpine
          
          
