name: otomasi deploy server
on: 
  push:
    branches:
      - main
  pull_request:
    types: [synchronized]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd prj
          sudo rm -rf deployBE16
          touch run.sh
          echo "git clone https://github.com/jackthepanda96/deployBE16.git" >> run.sh
          echo "cd deployBE16" >> run.sh
          echo "sudo go run main.go" >> run.sh
          sudo chmod +x run.sh
          ./run.sh
          rm run.sh
          
          
